// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment.Service.Data;

namespace Payment.Service.Migrations
{
    [DbContext(typeof(PaymentApplicationDbContext))]
    partial class PaymentApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Payment.Service.Entities.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amount = "5000",
                            cardNo = "1234567890",
                            cardType = "Debit",
                            customerId = "10",
                            description = "imergency payment"
                        },
                        new
                        {
                            id = 2,
                            amount = "7800",
                            cardNo = "99900033",
                            cardType = "Credit",
                            customerId = "20",
                            description = "bill payment"
                        },
                        new
                        {
                            id = 3,
                            amount = "9100",
                            cardNo = "44455666",
                            cardType = "Debit",
                            customerId = "30",
                            description = "notmal payment"
                        },
                        new
                        {
                            id = 4,
                            amount = "8000",
                            cardNo = "77711123",
                            cardType = "Credit",
                            customerId = "4",
                            description = "bank payment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
